import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :fotohaecker, FotohaeckerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # FIXME: dont put url here
  url: [host: "fschoenf.uber.space", port: 443]

# Do not print debug messages in production
config :logger, level: :info

config :fotohaecker, FotohaeckerWeb.Endpoint, static_url: [path: "/fh"]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
