name: check

on: push

jobs:
  mix_check:
    name: mix check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Cache Elixir Deps/Build
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            assets/node_modules
          key: elixir-deps-${{ runner.os }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('assets/pnpm-lock.yaml') }}-${{ hashFiles('lib/**/*.ex', 'lib/**/*.*ex', 'config/*.exs', 'mix.exs') }}
          restore-keys: |
            elixir-deps-${{ runner.os }}-${{ hashFiles('mix.lock') }}-
            elixir-deps-${{ runner.os }}

      - name: Run setup
        run: mix setup

      # - name: Compile Elixir deps
      #   run: mix deps.compile

      - name: Run check
        run: mix check --except dialyzer

      - name: Run dialyzer
        run: mix dialyzer
