name: check

on: push

jobs:
  mix_check:
    name: mix check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore deps and _build cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}

      - name: Run setup
        run: mix setup

      - name: Cache Elixir build
        uses: actions/cache@v2
        with:
          path: _build
          key: elixir-build-${{ runner.os }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('lib/**/*.ex', 'lib/**/*.*ex', 'config/*.exs', 'mix.exs') }}
          restore-keys: |
            elixir-build-${{ runner.os }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('.tool-versions') }}
            elixir-build-${{ runner.os }}

      - name: Compile Elixir deps
        run: mix deps.compile

      - name: Run check
        run: mix check
