name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Tools
        uses: asdf-vm/actions/install@v3

      - name: Cache Elixir Deps/Build
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            assets/node_modules
          key: elixir-deps-${{ runner.os }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('assets/pnpm-lock.yaml') }}-${{ hashFiles('lib/**/*.ex', 'lib/**/*.*ex', 'config/*.exs', 'mix.exs') }}
          restore-keys: |
            elixir-deps-${{ runner.os }}-${{ hashFiles('mix.lock') }}-
            elixir-deps-${{ runner.os }}
      - name: Run setup
        run: MIX_ENV=e2e mix setup
      - name: Cache E2E deps
        uses: actions/cache@v3
        with:
          path: test/e2e/node_modules
          key: e2e-deps-${{ runner.os }}-${{ hashFiles('test/e2e/package.json') }}-${{ hashFiles('test/e2e/pnpm-lock.yaml') }}
          restore-keys: |
            e2e-deps-${{ runner.os }}-${{ hashFiles('test/e2e/package.json') }}-${{ hashFiles('test/e2e/pnpm-lock.yaml') }}
            e2e-deps-${{ runner.os }}-${{ hashFiles('test/e2e/package.json') }}-
            e2e-deps-${{ runner.os }}
      - name: Run e2e setup
        run: |
          cd test/e2e
          pnpm install
          pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        working-directory: test/e2e
        run: pnpm test -- --project chromium --trace on home.spec.ts:49
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_MANAGEMENT_CLIENT_ID: ${{ secrets.AUTH0_MANAGEMENT_CLIENT_ID }}
          AUTH0_MANAGEMENT_CLIENT_SECRET: ${{ secrets.AUTH0_MANAGEMENT_CLIENT_SECRET }}
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
          STRIPE_CONNECT_CLIENT_ID: ${{ secrets.STRIPE_CONNECT_CLIENT_ID }}
          STRIPE_PRICE_ID: ${{ secrets.STRIPE_PRICE_ID }}
          E2E_USER_ID: ${{ secrets.E2E_USER_ID }}
          E2E_USER_EMAIL: ${{ secrets.E2E_USER_EMAIL }}
          E2E_USER_PASSWORD: ${{ secrets.E2E_USER_PASSWORD }}
          E2E_PHOTOGRAPHER_ID: ${{ secrets.E2E_PHOTOGRAPHER_ID }}
          E2E_PHOTOGRAPHER_EMAIL: ${{ secrets.E2E_PHOTOGRAPHER_EMAIL }}
          E2E_PHOTOGRAPHER_PASSWORD: ${{ secrets.E2E_PHOTOGRAPHER_PASSWORD }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: test/e2e/playwright-report/
          retention-days: 30
